### ISSUE TITLE
When i change the interaction type to redirect login not works 

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/active-directory-javascript-singlepageapp-angular#30]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

When i change the interaction type to redirect login not works but it is not getting success but in your angular 10 sample it is working but not in mine 

![image](https://user-images.githubusercontent.com/44996563/99379077-35826e80-28ee-11eb-9ca9-851f2ef9259b.png)

![image](https://user-images.githubusercontent.com/44996563/99379196-5e0a6880-28ee-11eb-8e55-ef8c2e3a0cc6.png)

## Library

- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`

## Description

Please provide your question here, including as much relevant details as possible.

Examples:
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by derisen** [comment]
@UmairAnhar hard to tell without seeing your configuration. Can you please share the contents of your `app.module.ts` and any steps to reproduce?

From the screenshot you shared (2nd one), it seems you are attempting to use auth code flow -is that correct? If so, that would be expected. This sample is using msal.js 1.x with implicit flow, so you need to make sure you've made the implicit flow setup as [instructed here](https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-angular#setup).

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/44996563/99619114-bd7c8b80-2a48-11eb-846b-b6238eb9dd41.png)
![image](https://user-images.githubusercontent.com/44996563/99619133-c66d5d00-2a48-11eb-8cfc-d6cc38043390.png)
![image](https://user-images.githubusercontent.com/44996563/99619151-cd946b00-2a48-11eb-9bf8-bb41c48fc4a7.png)

I did according to this sample

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample

And I did some change to the redirect login and it works that means I added this code to app.component.ts

![image](https://user-images.githubusercontent.com/44996563/99619280-219f4f80-2a49-11eb-92d1-24bd0d6e8541.png)

The issue is now it stays some time in the login page, after that redirect to a relevant page

So how can I ignore going to the login page after the successful login?

![image](https://user-images.githubusercontent.com/44996563/99619624-dcc7e880-2a49-11eb-9608-43ab62e7c96c.png)

2. How can i get the access token from the localstorage and the localstorage token key is changing according to the user who login

![image](https://user-images.githubusercontent.com/44996563/99622007-4991b180-2a4f-11eb-82d2-7a6a6e1694be.png)

**Comment by derisen** [comment]
@UmairAnhar ok, for (1), if you want to change the page to redirect after login, you first need to set the `navigateToLoginRequestUrl` [flag](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#using-the-config-object) to `true` in your configuration, register the `redirectUri` that you wish to be redirected after login, and `handleRedirectPromise` on that page accordingly. Take a look at the documentation [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#i-dont-understand-the-redirect-flow-how-does-the-handleredirectpromise-function-work) for details, and see this [similar issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2421).

For (2) You don't need to manually fetch the access token from browser storage. MSAL.js will handle it by itself if you use `acquireTokenSilent()` correctly.

p.s. something seems wrong in your 1st screenshot. You probably should pass the full endpoint for your API, like `https://localhost:44351/myapi` instead of `https://localhost:44351`

```typescript
protectedResourceMap.set('https://localhost:44351/myapi', ['api://xxxxx-xxxx-xxxx/access_as_user']));
```

**Comment by ghost** [comment]
(1) 
app.module.ts configuration

![image](https://user-images.githubusercontent.com/44996563/99866791-0f085000-2bda-11eb-9091-ef4bfa52d203.png)

i need to redirect to dashboard component so in the dashboard component in the oninit method i add the handleRedirectPromise 

![image](https://user-images.githubusercontent.com/44996563/99866817-44ad3900-2bda-11eb-91f4-b472c83fb1a5.png)


Note: still same no any change and also i have included handleRedirectPromise in the app.component.ts
